### ISSUE TITLE
Porting mod 1.20.1 ?

### ISSUE THREAD

**Issue by MrCookie112** [Plugway/MusicDiskDj#1]
Hello, thank you for this mod.

Currently most mods are still in 1.20.1 which means that this mode cannot be added to mod packs. Would it be possible to make it compatible with 1.20.1?

**Comment by Plugway** [comment]
Thanks for the feedback. 

I'll have the 1.20.1 version ready within the next 24 hours, possibly earlier.

**Comment by Plugway** [comment]
That was quicker than expected. I conducted some preliminary testing because there's no major difference between 1.20.2 and 1.20.1. Here's the [release](https://github.com/Plugway/MusicDiskDj/releases/tag/v1.0.0%2B1.20.1).
