### ISSUE TITLE
The J key does nothing

### ISSUE THREAD

**Issue by JeremyStarTM** [Plugway/MusicDiskDj#4]
I absolutely do not know if I skipped some vital information, but I cannot access the GUI, neither can I rebind it. Is it a bug or am I doing something wrong?

**Comment by Plugway** [comment]
This is related to issue #3

**Comment by JeremyStarTM** [comment]
How does input relate to file paths?

**Comment by Plugway** [comment]
The mod does not continue its execution and, in particular, does not initialize the key bind if it fails to create the directories and files necessary for proper operation. Perhaps it was worth explaining in more detail before closing the issue.

**Comment by JeremyStarTM** [comment]
Yeah, would've been better. Well thanks anyway :)
